ALTER TABLE gifts ADD COLUMN gift_type TEXT NOT NULL DEFAULT 'bouquet';
ALTER TABLE gifts ADD COLUMN gift_name TEXT NOT NULL DEFAULT '祝福花束';
ALTER TABLE gifts ADD COLUMN gift_image TEXT NOT NULL DEFAULT '';
